version: "3"
services:

  registry:
    container_name: scg-registry
    image: scg-registry:1.0.0
    build:
      context: ./scg-registry
      dockerfile: Dockerfile
    environment:
      VAR: A
    networks: 
      scg:
        ipv4_address: 172.21.0.2
    ports:
      - 8761:8761
    restart: "no"

  gatewayservice:
    container_name: gatewayservice
    image: gatewayservice:1.0.0
    build:
      context: ./scg-gateway-service
      dockerfile: Dockerfile
    environment:
      POSTS_ROUTE_URI: http://172.21.0.4:8080
      COMMENTS_ROUTE_URI: http://172.21.0.5:8080
      EUREKA_SERVER: http://172.21.0.2:8761/eureka
    networks: 
      scg:
        ipv4_address: 172.21.0.3
    ports:
      - 8082:8080
    restart: "no"

  posts:
    container_name: scg-posts
    image: scg-posts:1.0.0
    build:
      context: ./scg-posts-service
      dockerfile: Dockerfile
    environment:
      EUREKA_SERVER: http://172.21.0.2:8761/eureka
    networks: 
      scg:
        ipv4_address: 172.21.0.4
    ports:
      - 8083:8080
    restart: "no"


  comments:
    container_name: scg-comments
    image: scg-comments:1.0.0
    build:
      context: ./scg-comments-service
      dockerfile: Dockerfile
    environment:
      EUREKA_SERVER: http://172.21.0.2:8761/eureka
    networks: 
      scg:
        ipv4_address: 172.21.0.5
    ports:
      - 8084:8080
    restart: "no"

networks:
  scg:
    # driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1